// restaurantCategories.ts

// List of restaurant categories
const restaurantCategories: string[] = [
    // Cuisine-Based Categories
    "American",
    "Chinese",
    "Italian",
    "Mexican",
    "Japanese",
    "French",
    "Indian",
    "Mediterranean",
    "Thai",
    "Korean",
    "Vietnamese",
    "Greek",
    "Spanish",
    "Middle Eastern",
    "Caribbean",
    "African",
    "Filipino",
    "Turkish",
    "Brazilian",
    "Peruvian",
    "Ethiopian",
    "Lebanese",
    "Persian",
    "Russian",
    "Cuban",
    "Hawaiian",
    "German",
    "Polish",
    "Portuguese",
    "Swedish",
    "Dutch",
    "Malaysian",
    "Indonesian",
    "Pakistani",
    "Sri Lankan",
    "Argentinian",
    "Chilean",
    "Colombian",
    "Mongolian",
    "Nepalese",
    "Tibetan",
  
    // Dining Style Categories
    "Casual Dining",
    "Fine Dining",
    "Fast Food",
    "Buffet",
    "Food Truck",
    "Cafe",
    "Bistro",
    "Diner",
    "Gastropub",
    "Tavern",
    "Brasserie",
    "Speakeasy",
    "Rotisserie",
    "Steamboat",
    "Tapas Bar",
    "Supper Club",
  
    // Specialty Categories
    "Seafood",
    "Steakhouse",
    "BBQ",
    "Pizzeria",
    "Burger Joint",
    "Sushi Bar",
    "Dim Sum",
    "Hot Pot",
    "Noodle House",
    "Dessert Shop",
    "Ice Cream Parlor",
    "Juice Bar",
    "Tea House",
    "Coffee Shop",
    "Vegan",
    "Vegetarian",
    "Gluten Free",
    "Organic",
    "Kosher",
    "Halal",
    "Health Food",
    "Fusion Cuisine",
    "Gourmet Sandwiches",
    "Wine Bar",
    "Ramen House",
    "Taco Stand",
    "Churrascaria",
    "Doner Kebab",
    "Bubble Tea Shop",
    "Cevicheria",
    "Pancake House",
    "Waffle House",
    "Creperie",
    "Fondue Restaurant",
    "BBQ Pit",
    "Salad Bar",
    "Deli",
    "Bakery",
    "Chocolate Shop",
    "Cheese Shop",
    "Raw Food Restaurant",
    "Sustainable Seafood Restaurant",
    "Molecular Gastronomy Restaurant",
    "Charcuterie",
    "Gyoza Bar",
    "Kebab House"
  ];
  
  // List of local business categories
  const businessCategories: string[] = [
    "Grocery Store",
    "Supermarket",
    "Butcher Shop",
    "Farmers Market",
    "Convenience Store",
    "Florist",
    "Pharmacy",
    "Bakery",
    "Coffee Shop",
    "Bookstore",
    "Clothing Boutique",
    "Shoe Store",
    "Jewelry Store",
    "Home Decor",
    "Furniture Store",
    "Antique Shop",
    "Barbershop",
    "Hair Salon",
    "Nail Salon",
    "Spa",
    "Tattoo Parlor",
    "Dry Cleaner",
    "Laundromat",
    "Tailor",
    "Pet Store",
    "Veterinary Clinic",
    "Auto Repair Shop",
    "Car Dealership",
    "Bicycle Shop",
    "Hardware Store",
    "Electronics Store",
    "Music Store",
    "Sporting Goods Store",
    "Toy Store",
    "Art Gallery",
    "Printing Services",
    "Photography Studio",
    "Event Planning",
    "Wedding Services",
    "Coworking Space",
    "Tech Repair Services"
  ];
  
  export { restaurantCategories, businessCategories };
  