/**
 * Valid restrictions and favorite foods that a user can have.
 */

export const validRestrictions = [
  'vegetarian',
  'vegan',
  'gluten-free',
  'dairy-free',
  'nut-free',
  'halal',
];

export const foodCategories = [
  'pizza',
  'burger',
  'sushi',
  'pasta',
  'salad',
  'ice cream',
  'steak',
  'tacos',
  'ramen',
  'curry',
  'pancakes',
  'fried chicken',
  'bbq ribs',
  'falafel',
  'dumplings',
  'sandwich',
  'hot dog',
  'seafood platter',
  'burrito',
  'quesadilla',
  'mac and cheese',
  'grilled cheese',
  'samosa',
  'pho',
  'pad thai',
  'chili',
  'gumbo',
  'paella',
  'shawarma',
  'kebab',
  'lasagna',
  'risotto',
  'fish and chips',
  'bruschetta',
  'ceviche',
  'empanadas',
  'moussaka',
  'pierogi',
  'gnocchi',
  'poke bowl',
  'banh mi',
  'currywurst',
  'ratatouille',
  'baklava',
  'cheesecake',
  'crème brûlée',
  'gelato',
  'macaron',
  'chocolate cake',
  'fruit salad',
  'dim sum',
  'spring rolls',
  'tofu stir-fry',
  'sushi burrito',
  'chow mein',
  'lo mein',
  'bibimbap',
  'jambalaya',
  'steak tartare',
  'crab cakes',
  'oysters',
  'clam chowder',
  "shepherd's pie",
  'muffin',
  'croissant',
  'bagel',
  'pretzel',
  'smoothie bowl',
  'acai bowl',
  'poutine',
  'hot pot'
].sort();
