export const reservedUsernames: string[] = [
    "a", "about", "access", "account", "accounts", "add", "address", "adm", "admin",
    "advertising", "affiliate", "affiliates", "ajax", "analytics", "android",
    "api", "app", "apps", "archive", "atom", "auth", "authentication", "avatar",
    "backup", "banner", "banners", "bin", "billing", "blog", "blogs", "board", "bot",
    "bots", "business",
    "chat", "cache", "cadastro", "calendar", "campaign", "careers", "cgi", "client",
    "code", "comercial", "compare", "config", "connect", "contact", "contest",
    "css", "dashboard", "data", "db", "delete", "demo", "design", "developer",
    "dev", "directory", "doc", "docs", "domain", "download", "downloads",
    "edit", "editor", "email", "ecommerce",
    "forum", "forums", "faq", "favorite", "feed", "feedback", "file", "files", "ftp",
    "guest", "group", "groups",
    "help", "home", "homepage", "host", "hosting", "html", "http", "https", "info",
    "image", "images", "index", "invite", "intranet",
    "java", "javascript", "job", "jobs", "js",
    "log", "login", "logs", "logout",
    "mail", "mailer", "mailing", "manager", "marketing", "master", "media", "message",
    "mobile", "movie", "movies", "music", "my",
    "name", "network", "new", "news", "newsletter",
    "online", "operator", "order", "orders",
    "page", "pages", "panel", "password", "photo", "photos", "php", "plugin", "plugins",
    "post", "postmaster", "posts", "profile", "project", "projects", "promo",
    "public", "python",
    "random", "register", "registration", "root", "rss",
    "sale", "sales", "script", "scripts", "search", "security", "settings", "setup",
    "site", "sites", "sitemap", "smtp", "soporte", "ssh", "stage", "start",
    "subscribe", "support", "stat", "static", "stats", "store", "stores", "system",
    "tablet", "tech", "test", "theme", "themes", "tmp", "tools", "tv", "update",
    "upload", "user", "username", "usage",
    "video", "videos",
    "web", "webmail", "website", "websites", "webmaster", "workshop",
    "xxx",
    "yourname", "yourusername", "yoursite", "yourdomain"
];
